### ISSUE TITLE
Binary/build instructions

### ISSUE THREAD

**Issue by aioue** [sgallagher/sscg#5] opened 2018-01-02 18:02 UTC
Version in EPEL repo is very old (`0.4.1`).

Am on CentOS 7.4, any basic build instructions please?

**Comment by sgallagher** [comment] 2018-01-02 18:05
@aioue I'm working on getting it to build in EPEL, but the problem is that 0.5.0 and later require a newer version of the popt libraries than RHEL/CentOS ship. I'm looking into statically linking that. In the meantime, let me see if I can get you a COPR that will include an updated popt-libs package.

**Comment by sgallagher** [comment] 2018-01-02 18:22
@aioue As a temporary solution, you can probably use https://copr.fedorainfracloud.org/coprs/sgallagh/sscg/ 

Be aware that you will need the updated `popt` package from that repository as well (and it will upgrade your system copy, though to my understanding it is backwards-compatible).

Let me know if it works for you, please. I'll see about getting an official build with the statically-linked popt out soon.

**Comment by aioue** [comment] 2018-01-02 18:35
@sgallagher Thank you. That works for me on fresh CentOS 7.4 with latest updates. Installed `popt` then `sscg` and it ran successfully. Also fixes an issue I was having in official `0.4.1`  (`"sscg: error: argument --key-strength: invalid choice: '2048' (choose from 512, 1024, 2048, 4096)"`).

Thank you very much for your time and help.

**Comment by sgallagher** [comment] 2018-01-03 02:05
This is fixed in 2.3.1. The build system will now detect if the platform has a recent-enough version of popt available and will statically link 1.16 if not.

**Comment by sgallagher** [comment] 2018-01-03 02:06
Fixed by: https://github.com/sgallagher/sscg/commit/bc8b5b4c045c280a891b7bbecee68b5ef589a95c

**Closed by sgallagher** 2018-01-03 02:05 UTC

**Comment by sgallagher** [comment] 2018-01-03 03:05
Also on its way to EPEL 7 via https://bodhi.fedoraproject.org/updates/sscg-2.3.1-1.el7 (karma appreciated).

**Comment by aioue** [comment] 2018-01-03 15:13
Bodhi is new to me and I am unsure of the correct method to test the target there, even after reading docs.

No package match found when trying:
```bash
yum install sscg --enablerepo=epel-testing
```

**Comment by sgallagher** [comment] 2018-01-03 15:15
The updates-testing push hasn't happened yet, so it hasn't ended up in your local mirror. You can either download the package directly from https://koji.fedoraproject.org/koji/buildinfo?buildID=1012889 or wait until it shows up on the epel-testing mirror.

The official EPEL package won't require the popt from the COPR repo, so you should probably downgrade that back to the CentOS version.

**Comment by sgallagher** [comment] 2018-01-03 15:16
Once you've tested it, sign into Bodhi with a FAS account ( https://admin.fedoraproject.org/accounts if you don't yet have one) and answer the question "Is the update generally functional?"

**Comment by aioue** [comment] 2018-01-03 15:29
Successful install:
```bash
yum localinstall https://kojipkgs.fedoraproject.org//packages/sscg/2.3.1/1.el7/x86_64/sscg-2.3.1-1.el7.x86_64.rpm
```

Failure on test:
```bash
# which sscg
/bin/sscg
# rpm -qa | grep sscg
sscg-2.3.1-1.el7.x86_64
# # sscg --debug --lifetime 3650 --key-strength 2048 --cert-key-file /etc/cockpit/ws-certs.d/0-self-signed.cert --cert-file /etc/cockpit/ws-certs.d/0-self-signed.cert --ca-file /etc/cockpit/ws-certs.d/0-self-signed-ca.pem --hostname ip-1111.xx-yyy-1.compute.internal --organization f073c429a7456b53ec3e2c
==== Options ====
Certificate lifetime: 3650
Country: "US"
State or Principality: ""
Locality: ""
Organization: "f073c429a7456b53ec3e2c"
Organizational Unit: ""
Email Address: ""
Hostname: "ip-1111.xx-yyy-1.compute.internal"
=================
DEBUG: CA Key file path: (N/A)
Generating RSA key for private CA.
Generating CSR for private CA.
DEBUG: Creating SubjectKeyIdentifier
DEBUG: Writing CA CSR to ./debug-ca.csr
Signing CSR for private CA.
Generating RSA key for service certificate.
Generating CSR for service certificate.
DEBUG: Writing service certificate CSR to ./debug-svc.csr
Signing CSR for service certificate.
Writing svc private key to /etc/cockpit/ws-certs.d/0-self-signed.cert
Cannot allocate memory
```

**Comment by aioue** [comment] 2018-01-03 15:31
Dependency was installed during localinstall:

```
libtalloc                             x86_64                             2.1.9-1.el7                                base
```

**Comment by sgallagher** [comment] 2018-01-03 15:42
@aioue OK, that's an incorrect error message. Mind filing a separate bug on that?

The problem is that you're asking it to create a certificate inside a path that doesn't exist. Do `yum install cockpit-ws` (or `cockpit`) first. SSCG cannot know what ownership/permissions you want on that directory.

**Comment by aioue** [comment] 2018-01-03 15:47
100% success. Thank you very much for your time and help.

Clear in hindsight - fresh instance for testing, but no `cockpit` like yesterday.

Will submit a separate bug for the perms message. Thank you again.
